# Generated by Django 3.0.4 on 2020-05-06 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=25)),
                ('pub_date', models.IntegerField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(max_length=500)),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='Lib_App.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('recommended_for', models.ManyToManyField(related_name='recommendations', to='Lib_App.Profile')),
                ('reviewed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Lib_App.Book')),
                ('reviewer', models.ManyToManyField(related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.ManyToManyField(related_name='borrowed_books', to='Lib_App.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ManyToManyField(related_name='library', to='Lib_App.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='reading', to='Lib_App.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='wished',
            field=models.ManyToManyField(related_name='wish_list', to='Lib_App.Profile'),
        ),
    ]
