# Generated by Django 3.0.4 on 2020-05-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.IntegerField(null=True),
        ),
    ]
